### ISSUE TITLE
How to use code at the browser?

### ISSUE THREAD

**Issue by guest271314** [LinusU/cwasm-webp#1]
Am trying to use this code and https://github.com/LinusU/cwasm-lodepng in the browser, specifically at Firefox and Nightly where `CanvasRenderingContext2D` is not supported for `OffscreenCanvas` for the ability to manipulate pixels in a `Worker`, e.g., https://next.plnkr.co/plunk/gCjYSt.

`const instance = await WebAssembly.instantiate(wasmModule, importObject)` throws error for the `importObject`.

Have you been able to convert the nodejs-based code to `WebAssembly` code in the browser?

**Comment by guest271314** [comment]
Progress at the browser using import object at https://agniva.me/wasm/2018/05/17/wasm-hard-way.html. However, `memory` is not defined at `instance.exports`.

**Comment by guest271314** [comment]
@LinusU FWIW https://github.com/guest271314/decodePixelsFromOffscreenCanvas

**Comment by LinusU** [comment]
Sorry for not getting back to you earlier!

Potentially it would be possible to make this work in the browser as well, the problem is just how to package and deliver it. Would like to investigate if there is any Webpack support which would make this easy. Another approach would be to embed the wasm code inside the js file, maybe as base64...

**Comment by guest271314** [comment]
@LinusU The purpose of using the code at the browser is that Firefox has noot implemented `OffscreenCanvasRenderingContext2D` for `OffscreenCanvas` (see https://discourse.wicg.io/t/proposal-offscreenvideo/3952, https://bugzilla.mozilla.org/show_bug.cgi?id=1390089, et al.) to manipulate pixels of `ImageData` in a `Worker`.

Using a modified (some methods omitted https://gist.github.com/guest271314/db0bf90e4c9773bdcda9a3c92ba148c6) version achieves the expected output at Firefox. That is the simplest approach that have been able to achieve so far to get an `ImageData` from an `OffscreenCanvas`.
