### ISSUE TITLE
Possibility of adding encode functionality?

### ISSUE THREAD

**Issue by jhuckaby** [LinusU/cwasm-webp#3]
Hey Linus,

Thanks for this awesome library.  It seems to be the only one of its kind.  Would there be any possibility of adding an *encode* function, to compliment the decode?

I see there are several encode variants in libwebp, but I think all we would need is support for [WebPEncodeRGBA](https://chromium.googlesource.com/webm/libwebp/+/HEAD/doc/api.md#encoding-api).  Something like:

```js
const webp = require('@cwasm/webp');
webp.encode( data, 640, 480, 100 );
```

API docs draft:

### `encode(data, width, height, quality)`

- `data` ([`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array), required) - The RGBA data
- `width` The image width in pixels (required).
- `height` The image height in pixels (required).
- `quality` The desired image quality from 0 - 100 (required).
- No return value.

Thank you for your time!

**Comment by jhuckaby** [comment]
FYI, I went ahead and wrote my own, which borrows decoder and encoder WASMs from [Squoosh](https://github.com/GoogleChromeLabs/squoosh).

Link if interested: https://www.npmjs.com/package/webp-wasm

It works really well with node-canvas (example code included).

I'll go ahead and close this issue.  Thanks!

**Comment by LinusU** [comment]
Neat!

I've been thinking about adding encoding to all of my different image format packages, but potentially want to do it as separate packages in order to not add file size for people who only wants decoding...

btw. we have an `ImageData` class maintained by the node canvas team, that we'll probably use in the next major version of Canvas. You could use that instead of embedding your own: https://www.npmjs.com/package/@canvas/image-data

**Comment by jhuckaby** [comment]
Ah yes, that makes sense.  If you are interested, the Squoosh folks ([surma](https://github.com/surma) and [jakearchibald](https://github.com/jakearchibald)) have them all split out into decoders and encoders nicely:

https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs

Oh cool!  I'll look into using your `ImageData` implementation for sure.  Mine was just a placeholder until I found something better.  Thank you!
